version: "3.9"
services:
  sim:
    build:
      context: .
      dockerfile: dockerfile
    image: ros-humble-arm64:latest
    container_name: ros-sim
    platform: linux/arm64
    tty: true
    stdin_open: true
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_LOCALHOST_ONLY=0
      - CYCLONEDDS_URI=file:///etc/cyclonedds.xml
    volumes:
      - ./workspace:/workspace
    # command: ["/usr/local/bin/start-sim"]  # uncomment if not ENTRYPOINT

  novnc_proxy:
    build:
      context: .
      dockerfile: dockerfile.bridge
    image: novnc-bridge:latest
    container_name: vnc-bridge
    ports:
      - "6080:6080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TARGET_HOST=host.docker.internal
      - TARGET_PORT=5900
      - LISTEN_PORT=6080
      - NOVNC_WEB=/usr/share/novnc
    depends_on:
      - sim
    restart: unless-stopped
    command: ["/usr/local/bin/start-bridge"]
