version: "3.8"
services:
  ros:
    image: ros-humble-arm64
    container_name: ros-shell
    platform: linux/arm64
    tty: true
    stdin_open: true
    volumes:
      - ./workspace:/workspace
    tmpfs:
      - /tmp
