version: "3.9"
services:
  sim:
    build:
      context: .
      dockerfile: dockerfile

    container_name: ros-sim
    platform: linux/arm64
    image: ros-humble-arm64:latest

    tty: true
    stdin_open: true

    environment:
      - ROS_DOMAIN_ID=120
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_LOCALHOST_ONLY=0
    network_mode: host
    volumes:
      - ./workspace:/workspace
    ports:
      - "6080:6080" # expose noVNC
