version: "3.9"
services:
  core:
    build:
      context: .
      dockerfile: dockerfile
    image: ros-humble-arm64:latest
    container_name: ros-core
    tty: true
    stdin_open: true
    network_mode: host
    environment:
      ROS_DOMAIN_ID: 1
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_LOCALHOST_ONLY: 0
      DISPLAY: ${DISPLAY}
    volumes:
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
