version: "3.8"
services:
  sim:
    image: ros-humble-arm64
    container_name: ros-sim
    platform: linux/arm64
    tty: true
    stdin_open: true
    volumes:
      - ./workspace:/workspace
    tmpfs:
      - /tmp
    environment:
      - ROS_DOMAIN_ID=30
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_LOCALHOST_ONLY=0

  rviz:
    image: ros-humble-rviz
    container_name: ros-rviz
    platform: linux/arm64
    environment:
      - ROS_DOMAIN_ID=30
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_LOCALHOST_ONLY=0
    ports:
      - "6080:6080"   # expose noVNC
    depends_on:
      - sim
