#!/usr/bin/env bash
set -eo pipefail

# Env
export DISPLAY=:0
export QT_X11_NO_MITSHM=1
export LIBGL_ALWAYS_SOFTWARE=1
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export XDG_RUNTIME_DIR=/tmp/runtime-root
mkdir -p "$XDG_RUNTIME_DIR" && chmod 0700 "$XDG_RUNTIME_DIR"

# World
WORLD="${WORLD:-$1}"

# Clean X locks
rm -f /tmp/.X0-lock /tmp/.X11-unix/X0 || true
mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix

# Kill orphaned processes
pkill -f Xvfb || true
pkill -f x11vnc || true
pkill -f websockify || true

# X server
Xvfb :0 -screen 0 1280x720x24 -ac &
for i in {1..40}; do xdpyinfo -display :0 >/dev/null 2>&1 && break || sleep 0.25; done

# VNC
x11vnc -display :0 -nopw -forever -shared -rfbport 5900 -quiet &
for i in {1..40}; do (echo >/dev/tcp/127.0.0.1/5900) >/dev/null 2>&1 && break || sleep 0.25; done

# noVNC
websockify --web=/usr/share/novnc/ 0.0.0.0:6080 0.0.0.0:5900 &

echo '------------------'
echo 'NoVNC window: http://localhost:6080/vnc.html?resize=remote'
echo '------------------'

# source /opt/ros/humble/setup.bash
# [ -f ~/turtlebot3_ws/install/setup.bash ] && source ~/turtlebot3_ws/install/setup.bash

source ~/.bashrc
if [ $# -gt 0 ]; then
  exec "$@"
else
  exec ign gazebo "$WORLD"
fi
